version: "3.5"

services:
  ########################################################
  ### Frontend
  ########################################################

  acc-frontend:
    container_name: acc-frontend
    hostname: acc-frontend
    restart: on-failure
    image: fernandodumont/agent-control-center-frontend:1.0
    expose:
      - 80
    ports:
      - 80:80
    # volumes:
    #   - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - acc-net

  ########################################################
  ### Backend
  ########################################################

  acc-backend:
    container_name: acc-backend
    hostname: acc-backend
    restart: on-failure
    image: fernandodumont/agent-control-center-backend:1.0
    environment:
      - MONGODB_CONNECTION=mongodb://acc-mongodb:27017
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./data/backend/ansible/agent-files:/app/ansible/agent-files
      - ~/.ssh/aws-services.cer:/app/.ssh/aws-services.cer
    networks:
      - acc-net

  ########################################################
  ### Databases
  ########################################################

  acc-mongodb:
    image: fernandodumont/agent-control-center-mongodb:1.0
    container_name: acc-mongodb
    hostname: acc-mongodb
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb/data:/data
    networks:
      - acc-net

networks:
  acc-net:
